# --- DB ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/sgtc?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:sgtc}
spring.datasource.password=${DB_PASS:sgtc}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- CORS (Angular) ---
app.cors.allowed-origins=http://localhost:4200

# --- Upload ---
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# --- JWT ---
security.jwt.secret=${JWT_SECRET:troque-esse-segredo}
security.jwt.expiration-minutes=60

app.jwt.secret=${APP_JWT_SECRET:troque-esse-segredo}
app.jwt.issuer=sgtc
app.jwt.ttl-seconds=3600